# Generated by Django 2.2.7 on 2019-11-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('num_mat', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', help_text='Insira o nome completo do Aluno, com limite de 100 caracteres.', max_length=100, verbose_name='* Nome do Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', help_text='Insira o nome da Disciplina, com limite de 50 caracteres.', max_length=50, verbose_name='* Nome da Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nfunc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', help_text='Insira o nome completo do Professor, com limite de 100 caracteres.', max_length=100, verbose_name='* Nome do Professor')),
                ('end', models.CharField(default='', help_text='Insira o endereço completo do Professor, com limite de 100 caracteres.', max_length=100, verbose_name='* Endereço do Professor')),
                ('fone', models.CharField(default='(99) 99999-9999', help_text='Insira o telefone do Professor.', max_length=20, verbose_name='* Telefone do Professor')),
                ('titulacao', models.CharField(default='', help_text='Insira a titulação do Professor, com limite de 50 caracteres.', max_length=50, verbose_name='* Titulação do Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('nota_final', models.FloatField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('carga', models.IntegerField()),
                ('horario', models.TimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Professor')),
            ],
        ),
    ]
